# jekyll configuration

title: "Jekyll-asciidoc-quickstart"

currentVersion: "1.1.6"

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - hardbreaks!

# end of configuration
